version: "3"

services:
  blueberry-admin:
    build:
      context: ./dist
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://my-json-server.typicode.com/Yevgeniy-Dan/blueberry-dashboard-vite
    container_name: cmp
    image: oredata/cmp
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ../test-blueberry-admin-971ccb9a4b13.json:/app/keyfile.json
