const currentDate = new Date();
const currentDay = currentDate.getDate();
currentDate.setDate(currentDay + 1);
const tomorrowDay = currentDate.getDate();

export const todaysAppointments = [
  {
    id: "1",
    date: currentDay,
    time: currentDay,
    customerName: "John Doe",
    staff: "Alice",
    service: "Haircut",
    status: "Pending",
  },
  {
    id: "2",
    date: currentDay,
    time: currentDay,
    customerName: "Jane Smith",
    staff: "Bob",
    service: "Manicure",
    status: "Pending",
  },
  {
    id: "3",
    date: currentDay,
    time: currentDay,
    customerName: "Emma Johnson",
    staff: "Charlie",
    service: "Massage",
    status: "Pending",
  },
  {
    id: "4",
    date: currentDay,
    time: currentDay,
    customerName: "Michael Brown",
    staff: "David",
    service: "Facial",
    status: "Pending",
  },
  {
    id: "5",
    date: currentDay,
    time: currentDay,
    customerName: "Sarah Williams",
    staff: "Alice",
    service: "Pedicure",
    status: "Pending",
  },
  {
    id: "6",
    date: currentDay,
    time: currentDay,
    customerName: "James Taylor",
    staff: "Bob",
    service: "Waxing",
    status: "Pending",
  },
  {
    id: "7",
    date: currentDay,
    time: currentDay,
    customerName: "Olivia Martinez",
    staff: "Charlie",
    service: "Hair Coloring",
    status: "Pending",
  },
  {
    id: "8",
    date: currentDay,
    time: currentDay,
    customerName: "William Davis",
    staff: "David",
    service: "Facial",
    status: "Pending",
  },
  {
    id: "9",
    date: currentDay,
    time: currentDay,
    customerName: "Sophia Brown",
    staff: "Alice",
    service: "Massage",
    status: "Pending",
  },
  {
    id: "10",
    date: currentDay,
    time: currentDay,
    customerName: "Daniel Wilson",
    staff: "Bob",
    service: "Manicure",
    status: "Pending",
  },
];

export const tomorrowsAppointments = [
  {
    id: "11",
    date: tomorrowDay,
    time: tomorrowDay,
    customerName: "Ava Garcia",
    staff: "Charlie",
    service: "Pedicure",
    status: "Pending",
  },
  {
    id: "12",
    date: tomorrowDay,
    time: tomorrowDay,
    customerName: "Logan Rodriguez",
    staff: "David",
    service: "Waxing",
    status: "Pending",
  },
  {
    id: "13",
    date: tomorrowDay,
    time: tomorrowDay,
    customerName: "Mia Martinez",
    staff: "Alice",
    service: "Haircut",
    status: "Pending",
  },
  {
    id: "14",
    date: tomorrowDay,
    time: tomorrowDay,
    customerName: "Ethan Hernandez",
    staff: "Bob",
    service: "Hair Coloring",
    status: "Pending",
  },
  {
    id: "15",
    date: tomorrowDay,
    time: tomorrowDay,
    customerName: "Isabella Lopez",
    staff: "Charlie",
    service: "Facial",
    status: "Pending",
  },
  {
    id: "16",
    date: tomorrowDay,
    time: tomorrowDay,
    customerName: "Alexander Hill",
    staff: "David",
    service: "Massage",
    status: "Pending",
  },
  {
    id: "17",
    date: tomorrowDay,
    time: tomorrowDay,
    customerName: "Abigail Scott",
    staff: "Alice",
    service: "Manicure",
    status: "Pending",
  },
  {
    id: "18",
    date: tomorrowDay,
    time: tomorrowDay,
    customerName: "Noah Green",
    staff: "Bob",
    service: "Waxing",
    status: "Pending",
  },
  {
    id: "19",
    date: tomorrowDay,
    time: tomorrowDay,
    customerName: "Emily Adams",
    staff: "Charlie",
    service: "Haircut",
    status: "Pending",
  },
  {
    id: "20",
    date: tomorrowDay,
    time: tomorrowDay,
    customerName: "Jameson Baker",
    staff: "David",
    service: "Pedicure",
    status: "Pending",
  },
];
