import { ServiceModel } from "../../../redux/services/models";

export const serviceData: ServiceModel[] = [
  {
    id: "1",
    name: "Service 1",
    duration: "1 hour",
    price: "50",
    currencyCode: "USD",
    isNoPreferenceEnabled: true,
    staffMembers: [],
  },
  {
    id: "2",
    name: "Service 2",
    duration: "45 minutes",
    price: "40",
    currencyCode: "USD",
    isNoPreferenceEnabled: false,
    staffMembers: [],
  },
  {
    id: "3",
    name: "Service 3",
    duration: "30 minutes",
    price: "30",
    currencyCode: "USD",
    isNoPreferenceEnabled: true,
    staffMembers: [],
  },
  {
    id: "4",
    name: "Service 4",
    duration: "1.5 hours",
    price: "60",
    currencyCode: "USD",
    isNoPreferenceEnabled: true,
    staffMembers: [],
  },
  // {
  //   id: "5",
  //   name: "Service 5",
  //   duration: "1 hour",
  //   price: "$50",
  //   staffMembers: [],
  // },
  // {
  //   id: "6",
  //   name: "Service 6",
  //   duration: "45 minutes",
  //   price: "$40",
  //   staffMembers: [],
  // },
  // {
  //   id: "7",
  //   name: "Service 7",
  //   duration: "30 minutes",
  //   price: "$30",
  //   staffMembers: [],
  // },
  // {
  //   id: "8",
  //   name: "Service 8",
  //   duration: "1.5 hours",
  //   price: "$60",
  //   staffMembers: [],
  // },
  // {
  //   id: "9",
  //   name: "Service 9",
  //   duration: "1 hour",
  //   price: "$50",
  //   staffMembers: [],
  // },
  // {
  //   id: "10",
  //   name: "Service 10",
  //   duration: "45 minutes",
  //   price: "$40",
  //   staffMembers: [],
  // },
  // {
  //   id: "11",
  //   name: "Service 11",
  //   duration: "30 minutes",
  //   price: "$30",
  //   staffMembers: [],
  // },
  // {
  //   id: "12",
  //   name: "Service 12",
  //   duration: "1.5 hours",
  //   price: "$60",
  //   staffMembers: [],
  // },
  // {
  //   id: "13",
  //   name: "Service 13",
  //   duration: "1 hour",
  //   price: "$50",
  //   staffMembers: [],
  // },
  // {
  //   id: "14",
  //   name: "Service 14",
  //   duration: "45 minutes",
  //   price: "$40",
  //   staffMembers: [],
  // },
  // {
  //   id: "15",
  //   name: "Service 15",
  //   duration: "30 minutes",
  //   price: "$30",
  //   staffMembers: [],
  // },
  // {
  //   id: "16",
  //   name: "Service 16",
  //   duration: "1.5 hours",
  //   price: "$60",
  //   staffMembers: [],
  // },
  // {
  //   id: "17",
  //   name: "Service 17",
  //   duration: "1 hour",
  //   price: "$50",
  //   staffMembers: [],
  // },
  // {
  //   id: "18",
  //   name: "Service 18",
  //   duration: "45 minutes",
  //   price: "$40",
  //   staffMembers: [],
  // },
  // {
  //   id: "19",
  //   name: "Service 19",
  //   duration: "30 minutes",
  //   price: "$30",
  //   staffMembers: [],
  // },
  // {
  //   id: "20",
  //   name: "Service 20",
  //   duration: "1.5 hours",
  //   price: "$60",
  //   staffMembers: [],
  // },
];
