import { ServiceModel } from "../../../redux/services/models";

export const serviceData: ServiceModel[] = [
  {
    id: "1",
    name: "Service 1",
    duration: "1 hour",
    price: "50",
    currencyCode: "USD",
    isNoPreferenceEnabled: true,
    staffMembers: [],
  },
  {
    id: "2",
    name: "Service 2",
    duration: "45 minutes",
    price: "40",
    currencyCode: "USD",
    isNoPreferenceEnabled: false,
    staffMembers: [],
  },
  {
    id: "3",
    name: "Service 3",
    duration: "30 minutes",
    price: "30",
    currencyCode: "USD",
    isNoPreferenceEnabled: true,
    staffMembers: [],
  },
  {
    id: "4",
    name: "Service 4",
    duration: "1.5 hours",
    price: "60",
    currencyCode: "USD",
    isNoPreferenceEnabled: true,
    staffMembers: [],
  },
  {
    id: "5",
    name: "Service 5",
    duration: "1 hour",
    price: "$50",
    currencyCode: "USD", // Add currency code for each service
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "6",
    name: "Service 6",
    duration: "45 minutes",
    price: "$40",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "7",
    name: "Service 7",
    duration: "30 minutes",
    price: "$30",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "8",
    name: "Service 8",
    duration: "1.5 hours",
    price: "$60",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "9",
    name: "Service 9",
    duration: "1 hour",
    price: "$50",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "10",
    name: "Service 10",
    duration: "45 minutes",
    price: "$40",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "11",
    name: "Service 11",
    duration: "30 minutes",
    price: "$30",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "12",
    name: "Service 12",
    duration: "1.5 hours",
    price: "$60",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "13",
    name: "Service 13",
    duration: "1 hour",
    price: "$50",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "14",
    name: "Service 14",
    duration: "45 minutes",
    price: "$40",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "15",
    name: "Service 15",
    duration: "30 minutes",
    price: "$30",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "16",
    name: "Service 16",
    duration: "1.5 hours",
    price: "$60",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "17",
    name: "Service 17",
    duration: "1 hour",
    price: "$50",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "18",
    name: "Service 18",
    duration: "45 minutes",
    price: "$40",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "19",
    name: "Service 19",
    duration: "30 minutes",
    price: "$30",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "20",
    name: "Service 20",
    duration: "1.5 hours",
    price: "$60",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "21",
    name: "Service 21",
    duration: "2 hours",
    price: "$80",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
  {
    id: "22",
    name: "Service 22",
    duration: "1.25 hours",
    price: "$65",
    currencyCode: "USD",
    staffMembers: [],
    isNoPreferenceEnabled: false,
  },
];
